# Generated by Django 2.0.1 on 2018-01-07 01:54

from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20180105_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=forum.models.get_next_post_datetime),
        ),
    ]
