# Generated by Django 2.0.1 on 2018-01-07 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20180107_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='created',
        ),
    ]
